[versions]
kotlin-plugin = "2.1.10"
ksp = "2.1.10-1.0.29"
apollo = "4.1.1"
ktor = "3.0.0"
spring = "3.3.3"

[libraries]
kgp = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-plugin" }
kgp-min = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version = "1.9.0" }
java-diff-utils = { module = "io.github.java-diff-utils:java-diff-utils", version = "4.12" }
gradle-api-min = { group = "dev.gradleplugins", name = "gradle-api", version = "8.0" }
apollo-ast = { group = "com.apollographql.apollo", name = "apollo-ast", version.ref = "apollo" }
apollo-compiler = { group = "com.apollographql.apollo", name = "apollo-compiler", version.ref = "apollo" }
apollo-api = { group = "com.apollographql.apollo", name = "apollo-api", version.ref = "apollo" }
apollo-execution = { group = "com.apollographql.apollo", name = "apollo-execution", version.ref = "apollo" }
atomicfu = "org.jetbrains.kotlinx:atomicfu:0.24.0"
kotlinpoet = "com.squareup:kotlinpoet:1.18.0"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.1"
arrowCore = "io.arrow-kt:arrow-core:1.2.4"
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref ="ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref ="ktor" }
ktor-server-cors = { group = "io.ktor", name = "ktor-server-cors", version.ref ="ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-server-websockets = { group = "io.ktor", name = "ktor-server-websockets", version.ref ="ktor" }
slf4j-simple = "org.slf4j:slf4j-simple:2.0.13"
slf4j-nop = "org.slf4j:slf4j-nop:2.0.13"
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-implementation = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "ksp" }
ksp-gradle = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" } # the Kotlin plugin resolves the version
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-plugin" }
http4k-bom = "org.http4k:http4k-bom:5.8.0.0"
http4k-core = { module = "org.http4k:http4k-core" }
http4k-realtime-core = { module = "org.http4k:http4k-realtime-core" }
http4k-server-undertow = { module = "org.http4k:http4k-server-undertow" }
http4k-server-netty = { module = "org.http4k:http4k-server-netty" }
librarian-gradle-plugin = "com.gradleup.librarian:librarian-gradle-plugin:0.0.8-SNAPSHOT-cd822254de75426f8f047a50bae467da872cc912"
apollo-execution-runtime = { module = "com.apollographql.execution:apollo-execution-runtime" }
apollo-execution-subgraph = { module = "com.apollographql.execution:apollo-execution-subgraph" }
spring-webflux = "org.springframework:spring-webflux:6.1.10"
wire-gradle-plugin = "com.squareup.wire:wire-gradle-plugin:5.3.1"
kotlinx-serialization-core = "org.jetbrains.kotlinx:kotlinx-serialization-core:1.7.3"
[plugins]
kgp-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
apollo-execution = { id = "com.apollographql.execution" }